version: 0.2
env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - npm install --arch=x64 --platform=linux --target=14.16.1
      - npm prune
  build:
    commands:
      - npx serverless deploy
      