version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm prune
  build:
    commands:
      - npx serverless deploy
  post_build:
    commands:
      - npm install -g redoc-cli
      - redoc-cli bundle api-oas30-postman.json
      - aws s3 cp --sse AES256 redoc-static.html s3://oceanarchive-demo-client/api.html
      