version: "3.3"
services:
  tba21_test_postgres:
    container_name: tba21_test_postgres
    image: tba21_test_postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tba21
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5432:5432"
