version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    machine: true
    docker:
      - image: circleci/node:lts

    steps:
      - checkout

      # NPM stuff
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm
          command: npm install

      - run:
          name: Install JEST
          command: sudo npm install -g jest

      # Clone the schema repo
      - run:
          name: Clone Schema
          command: git clone --branch dev https://github.com/AcrossTheCloud/TBA21-schema.git ~/project/docker/schema

      # Do Docker stuff
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Start postgres container
          command: docker-compose up -d

      # Wait for PG
      - run:
          name: Waiting for Postgres to be ready
          command: sleep 15

      - run:
          name: Run unit tests
          command: jest --coverage

      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: coverage/coverage-final.json
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
