version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:

    docker:
      - image: circleci/node:lts
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/tba21
      - image: circleci/postgres:11-alpine-postgis-ram
        environment:
          POSTGRES_DB: tba21
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout

      # PG CLIENT
      - run: curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      - run: echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" | sudo tee  /etc/apt/sources.list.d/pgdg.list
      - run: sudo apt update
      - run: sudo apt -y upgrade
      - run: sudo apt -y install postgresql-client

      # NPM stuff
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm
          command: npm install

      - run:
          name: Install JEST
          command: sudo npm install -g jest

      # Clone the schema repo
      - run:
          name: Clone Schema
          command: git clone --branch dev https://github.com/AcrossTheCloud/TBA21-schema.git ~/project/docker/schema

      # Seed the database
      - run:
          name: Add Schema to DB
          command: psql -d $TEST_DATABASE_URL -f ~/project/docker/schema/schema.sql
      - run:
          name: Add Schema to DB
          command:
            for f in ~/project/docker/schema/seeds/*.sql;
              do
                psql -d $TEST_DATABASE_URL -f "$f";
              done;

      - run:
          name: Run unit tests
          command: jest --coverage

      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: coverage/coverage-final.json
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
